export * from "./catalogPage"
export * from "./contentPage"
export * from "./searchPage"
export * from "./notFound"
export * from "./newPage"
export * from "./topPage"
export * from "./favoritesPage"
export * from "./home"
